# frozen_string_literal: true

require_relative 'jsonable'

module CfnDsl
  # Handles Resource objects
  class ResourceDefinition < JSONable
    dsl_attr_setter :Type, :UpdateReplacePolicy, :DeletionPolicy, :Condition, :Metadata
    dsl_content_object :Property, :UpdatePolicy, :CreationPolicy

    # Declare references that will be generated by transforms/macros
    # @param patterns [Array<Symbol, String, Regexp>] patterns to match generated resource names
    # @example
    #   Serverless_Function(:myfunc) do
    #     AutoPublishAlias 'live'
    #     generated_refs :myfuncAliaslive, /myfuncVersion[a-f0-9]+/
    #   end
    def generated_refs(*patterns)
      @generated_refs ||= []
      @generated_refs.concat(patterns)
    end

    # Hook method for subclasses to automatically generate refs based on properties
    # Override this in resource-specific patches to add automatic ref detection
    # @return [Array<Symbol, String, Regexp>] patterns to match generated resource names
    def auto_generated_refs
      []
    end

    def add_tag(name, value, propagate = nil)
      send(:Tag) do
        Key name
        Value value
        PropagateAtLaunch propagate unless propagate.nil?
      end
    end

    # DependsOn can be a single value or a list
    def DependsOn(value)
      case @DependsOn
      when nil
        @DependsOn = value
      when Array
        @DependsOn << value
      else
        @DependsOn = [@DependsOn, value]
      end
      if @DependsOn.is_a?(Array)
        @DependsOn.flatten!
        @DependsOn.uniq!
      end
      @DependsOn
    end

    def condition_refs
      [@Condition].flatten.compact.map(&:to_s)
    end

    def all_refs
      [@DependsOn].flatten.compact.map(&:to_s)
    end
  end
end
