Metrics/LineLength:
  Max: 160

# TODO Temp fix this
Metrics/CyclomaticComplexity:
  Max: 30

# TODO Temp fix this
Metrics/PerceivedComplexity:
  Max: 30

# TODO Temp fix this
Metrics/AbcSize:
  Max: 92

# TODO Temp fix this
Metrics/MethodLength:
  Max: 100

# TODO Temp fix this
Metrics/ClassLength:
  Max: 200

# TODO Temp fix this
Style/Documentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: true

# Due to our @Properties style instance names
Style/VariableName:
  Enabled: false

# We are a DSL
Style/MethodName:
  Enabled: false

# Lone String
Lint/Void:
  Enabled: false
