Layout/LineLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

# Due to our @Properties style instance names
Naming/VariableName:
  Enabled: false

# We are a DSL
Naming/MethodName:
  Enabled: false

# Lone String
Lint/Void:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

# crashing in 0.85.0
Lint/MixedRegexpCaptureTypes:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  Exclude:
    - 'tmp/**/*'
