name: Spec

on:
  push:
    branches:
      - "**"
  pull_request:
env:
  BUNDLE_FROZEN: "true"
jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.3', '3.4']

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
